name: Carrie Keenan
favicon: null
layout_spectrum: 0.7448
typography_spectrum: 0.69106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdff'
    - '#03043a'
    - '#a9adb6'
    - '#65396c'
    - '#fc9d2a'
  brandStrength: 0.09084991132840514
  lightness: 0.8649149036500603
  saturation: 0.59775117225945
  rhythmicContrast: 0.8867602883838117
purpose: []
